app:
  debug: True
  version: "1.0.0"
  name: "app server api"
  description: "app server api"
  prefix: "/api/v1"
  host: "0.0.0.0"
  address: "127.0.0.1"
  port: 8888

mariadb: "mysql://{user_name}:{password}@{host}:{port}/{db_name}?charset=utf8mb4"
redis: "redis://:{password}@{host}:{port}/{db}?encoding=utf-8"

expires: &exp
  # 5分钟
  S_5: 300
  # 20分钟
  S_20: 1200
  # 2小时
  H_2: 7200
  # 2天
  D_2: 172800
  # 7天
  D_7: 604800
  # 一个月
  M_1: 18144000

auth:
  secret_key: "oG0[dP1|rB2$pC2^lC4_"
  token_type: "Bearer"
  algorithm: "HS256"
  <<: *exp